paths:
  jquery: 'jquery'
  underscore: 'underscore'
  backbone: 'backbone'
  chaplin: 'chaplin'
shim:
  'jquery':
    exports: '$'
  'underscore':
    exports: '_'
  'backbone':
    deps: ['underscore', 'jquery']
    exports: 'Backbone'
